---
apiVersion: v1
kind: Service
metadata:
  name: fazlb443
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.49.2
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 38443
    targetPort: 443
  selector:
    app: fortianalyzer
  type: LoadBalancer
