apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "cidata"
spec:
  source:
    http:
      url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/cidata.iso"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "1000Mi"
