apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: faz
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: faz
        app: faz
    spec:
      nodeSelector: #nodeSelector matches nodes where performance key has high as value.
        nested: "true"
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - disk:
              bus: virtio
            name: disk1
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        resources:
          requests:
            memory: 8000M
      readinessProbe:
        tcpSocket:
          port: 443
        initialDelaySeconds: 180
        periodSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /
          port: 443
          scheme: HTTPS
        initialDelaySeconds: 240
        periodSeconds: 10
        failureThreshold: 3
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: faz
      - name: disk1
        persistentVolumeClaim:
          claimName: fazlogvm
      - name: cloudinitdisk
        persistentVolumeClaim:
          claimName: cidata-pvc
    dataVolumeTemplates:
    - metadata:
        name: cidata-dv
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        source:
          http:
            url:  "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/cidata.iso"
