apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "faz"
spec:
  source:
    http:
      #url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/faz707.qcow2" # S3 or GCS
      #url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/fazoracle722.qcow2" # S3 or GCS
      url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/fazibm707.qcow2" # S3 or GCS
      #url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/faz74.qcow2" # S3 or GCS
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "5000Mi"
