#https://docs.fortinet.com/document/fortimanager/7.0.0/fortimanager-ports/290737/incoming-ports
#514, logging, OFTP , both TCP and UDP  , TCP 8443 Log from chromebook, , 8080, SOAP , TCP/445 DC polling 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortimanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortimanager
  template:
    metadata:
      labels:
        app: fortimanager
    spec:
      nodeSelector: 
        linux: "true"
      containers:
        - name: fortimanager
          image: fortinet/fortimanager:7.0.7
          ports:
            - containerPort: 541
            - containerPort: 443
            - containerPort: 22
            - containerPort: 23
            - containerPort: 8888
            - containerPort: 8889
            - containerPort: 8890
            - containerPort: 8080
            - containerPort: 8080
            - containerPort: 8123
            - containerPort: 9009
            - containerPort: 9000
            - containerPort: 8793
            - containerPort: 9999
            - containerPort: 8443
            - containerPort: 514
            - containerPort: 514
              protcol: UDP
            - containerPort: 26443
            - containerPort: 161
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - ALL
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 240
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: var-fmgt100
              mountPath: /var
            - name: data-fmgt100
              mountPath: /data
      volumes:
        - name: var-fmgt100
          persistentVolumeClaim:
            claimName: fmgvar
        - name: data-fmgt100
          persistentVolumeClaim:
            claimName: fmgdata

