#https://docs.fortinet.com/document/fortimanager/7.0.0/fortimanager-ports/290737/incoming-ports
#514, logging, OFTP , both TCP and UDP  , TCP 8443 Log from chromebook, , 8080, SOAP , TCP/445 DC polling 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortimanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortimanager
  template:
    metadata:
      labels:
        app: fortimanager
    spec:
      nodeSelector: 
        linux: "true"
      containers:
        - name: fortimanager
          #image: fortinet/fortimanager:7.0.7
          image: interbeing/myfmg:707
          ports:
            - containerPort: 541
            - containerPort: 443
            - containerPort: 22
            - containerPort: 23
            - containerPort: 8888
            - containerPort: 8889
            - containerPort: 8890
            - containerPort: 8080
            - containerPort: 8080
            - containerPort: 8123
            - containerPort: 9009
            - containerPort: 9000
            - containerPort: 8793
            - containerPort: 9999
            - containerPort: 8443
            - containerPort: 514
            - containerPort: 514
              protocol: UDP
            - containerPort: 26443
            - containerPort: 161
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - ALL
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - "nc -zc 127.0.0.1 8080 && nc -zc 127.0.0.1 443 && nc -zc 127.0.0.1 22 && nc -zc 127.0.0.1 80 && nc -zc 127.0.0.1 541 && nc -zc 127.0.0.1 8443 && nc -zc 127.0.0.1 8900 && nc -zc 127.0.0.1 53"
            initialDelaySeconds: 300
            failureThreshold: 3
            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 443
#              scheme: HTTPS
#            initialDelaySeconds: 300
#            periodSeconds: 10
#            failureThreshold: 3
          volumeMounts:
            - name: var-fmgt100
              mountPath: /var
            - name: data-fmgt100
              mountPath: /data
      volumes:
        - name: var-fmgt100
          persistentVolumeClaim:
            claimName: fmgvar
        - name: data-fmgt100
          persistentVolumeClaim:
            claimName: fmgdata
