---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fortimanager-tls-fmg
spec:
  secretName: fortimanager-tls-fmg
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: selfsigned-issuer-fmg
    kind: ClusterIssuer
  commonName: fmgminikube
  dnsNames:
  - fmgminikube
