apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fmgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fmgvar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
