#https://docs.fortinet.com/document/fortianalyzer/7.0.0/fortianalyzer-ports/290737/incoming-ports
#514, logging, OFTP , both TCP and UDP  , TCP 8443 Log from chromebook, , 8080, SOAP , TCP/445 DC polling 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortianalyzer-deployment
  namespace: fortinet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortianalyzer
  template:
    metadata:
      labels:
        app: fortianalyzer
    spec:
#      initContainers:
#      - name: init-sleep
#        image: busybox
#        command: ['sh', '-c', 'sleep 1200']
      nodeSelector: 
        linux: "true"
      containers:
        - name: fortianalyzer
          image: fortinet/fortianalyzer:7.0.7
#          resources:
#            limits:
#              cpu: "4"
#              memory: "8000Mi"
#            requests:
#              cpu: "2"
#              memory: "8000Mi"
          ports:
            - containerPort: 541
            - containerPort: 443
            - containerPort: 22
            - containerPort: 23
            - containerPort: 8888
            - containerPort: 8889
            - containerPort: 8890
            - containerPort: 8080
            - containerPort: 8080
            - containerPort: 8123
            - containerPort: 9009
            - containerPort: 9000
            - containerPort: 8793
            - containerPort: 9999
            - containerPort: 8443
            - containerPort: 514
            - containerPort: 514
              protocol: UDP
            - containerPort: 26443
            - containerPort: 161
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - ALL
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 240
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 480
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: var-fazt100
              mountPath: /var
            - name: data-fazt100
              mountPath: /data
      volumes:
        - name: var-fazt100
          persistentVolumeClaim:
            claimName: fazvar
        - name: data-fazt100
          persistentVolumeClaim:
            claimName: fazdata

