---
apiVersion: v1
kind: Service
metadata:
  name: fazcontainerhttps
spec:
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  ports:
  - port: 443
    name: webgui
    protocol: TCP
    targetPort: 443
  - port: 22
    name: ssh
    protocol: TCP
    targetPort: 22
  selector:
    app: fortianalyzer
  type: LoadBalancer

