apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fazdata
  namespace: fortinet
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fazvar
  namespace: fortinet
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
