#https://docs.fortinet.com/document/fortianalyzer/7.0.0/fortianalyzer-ports/290737/incoming-ports
#514, logging, OFTP , both TCP and UDP  , TCP 8443 Log from chromebook, , 8080, SOAP , TCP/445 DC polling 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortianalyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortianalyzer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fortianalyzer
    spec:
#      initContainers:
#      - name: init-sleep
#        image: busybox
#        command: 
#        - /bin/sh
#        - -c
#        - |
#          unset FAZCONTAINERHTTPS_PORT_28889_TCP_PORT

      containers:
        - name: fortianalyzer
#          image: fortinet/fortianalyzer:7.2.2
          image: interbeing/myfmg:faz7248590
          imagePullPolicy: IfNotPresent
          command:
          - /sbin/init
#          image: nginx:latest
#          resources:
#            limits:
#              cpu: "2"
#              memory: "16000Mi"
#            requests:
#              cpu: "2"
#              memory: "8000Mi"
#          command:
#          - /bin/sh
#          - -c
#          - |
          securityContext:
            capabilities:
              add:
                - ALL
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: var-fazt100
              mountPath: /var
            - name: data-fazt100
              mountPath: /data
      volumes:
        - name: var-fazt100
          persistentVolumeClaim:
            claimName: fazvar
        - name: data-fazt100
          persistentVolumeClaim:
            claimName: fazdata

