#443/TCP,8443/TCP,514/TCP,541/TCP,8123
---
apiVersion: v1
kind: Service
metadata:
  name: fazcontainerhttps
spec:
#  sessionAffinity: ClientIP
  ports:
  - port: 443
    name: webgui
    protocol: TCP
    targetPort: 443
  - port: 514
    name: oftpd
    protocol: TCP
    targetPort: 514
  - port: 541
    name: fgfm
    protocol: TCP
    targetPort: 541
  - port: 8123
    name: mast
    protocol: TCP
    targetPort: 8123
  - port: 8443
    name: webg
    protocol: TCP
    targetPort: 8443
  selector:
    app: fortianalyzer
  type: ClusterIP
 
