---
apiVersion: v1
kind: Service
metadata:
  name: fmgcontainerhttps
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 2443
    name: webgui
    protocol: TCP
    targetPort: 2443
  - port: 222
    name: ssh
    protocol: TCP
    targetPort: 222
  - port: 28888
    name: weba
    protocol: TCP
    targetPort: 28888
  - port: 28889
    name: webb
    protocol: TCP
    targetPort: 28889
  - port: 28890
    name: webc
    protocol: TCP
    targetPort: 28890
  - port: 28080
    name: soap
    protocol: TCP
    targetPort: 28080
  - port: 2514
    name: oftpd
    protocol: TCP
    targetPort: 2514
  - port: 2541
    name: fgfm
    protocol: TCP
    targetPort: 2541
  - port: 28793
    name: mast
    protocol: TCP
    targetPort: 28793
  - port: 28443
    name: webg
    protocol: TCP
    targetPort: 28443
  - port: 29999
    name: webh
    protocol: TCP
    targetPort: 29999
  - port: 2161
    name: syslog
    protocol: UDP
    targetPort: 2161
  - port: 2542
    name: fgfm2
    protocol: TCP
    targetPort: 2542
  - port: 2543
    name: fgfm3
    protocol: TCP
    targetPort: 2543
  - port: 2544
    name: fgfm4
    protocol: TCP
    targetPort: 2544
  - port: 2545
    name: fgfm5
    protocol: TCP
    targetPort: 2545
  - port: 2546
    name: fgfm6
    protocol: TCP
    targetPort: 2546
  selector:
    app: fortimanager
  type: ClusterIP
