apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fazdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fazvar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
